from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class StrategyComponent(BaseModel):
    category: str = Field(..., description="Name of the strategy module, e.g. entry/stop_loss/etc")
    objective: str = Field(..., description="High-level goal of this module")
    rules: List[str] = Field(default_factory=list, description="Concrete rules or indicators leveraged")


class StrategyPlan(BaseModel):
    components: List[StrategyComponent] = Field(default_factory=list)
    yaml: str = Field(..., description="YAML representation following the unified schema")
    diagram: str = Field(..., description="Simplified text diagram describing the strategy flow")
    reasoning: Optional[str] = Field(
        default=None, description="Optional commentary generated by the LLM explaining the plan"
    )


class ChatMessage(BaseModel):
    message: str = Field(..., description="End-user strategy requirement prompt")
    symbol: str = Field(..., description="Ticker to backtest, e.g. 000001.SZ")
    start_date: str = Field(..., description="Start date for backtest, YYYY-MM-DD")
    end_date: str = Field(..., description="End date for backtest, YYYY-MM-DD")
    initial_cash: float = Field(100000.0, description="Initial cash for the backtest in CNY")


class ChatResponse(BaseModel):
    plan: StrategyPlan
    backtest_summary: str
    interpretation: str
    raw_metrics: dict


class BacktestRequest(BaseModel):
    config_yaml: str
    symbol: str
    start_date: str
    end_date: str
    initial_cash: float = 100000.0


class BacktestResponse(BaseModel):
    summary: str
    metrics: dict
